NEW: Add optional phpstan execution to PHPCS_TEST
silverstripe/silverstripe-travis-shared pull request #12
Opened 2021-02-25 22:37 UTC by sminnee

PHPStan is a static analyser that may be of use to some repositories.
Notably, I've got a small, passing PHPStan level 1 PR to submit to
framework.

This will include a phpstan call in the PHPCS_TEST build, if
phpstan.neon.dist exists.

I've opted not to split it out as a separate build var to reduce the
number of separate builds. This is essentially another form of
sophisticated linting, hence putting it with phpcs.

2021-02-25 23:42 UTC, dnsl48 requested changes

2021-02-25 23:42 UTC, dnsl48 commented on config/base.yml
> +  - if [[ $PHPCS_TEST && -f phpstan.neon.dist ]]; then vendor/bin/phpstan analyse; fi
What's the benefit of coupling it with phpcs? Shouldn't it be completely separate?

2021-02-25 23:43 UTC, dnsl48 commented
> I've opted not to split it out as a separate build var to reduce the
number of separate builds.

I guess we might add another variable to the existing builds?

2021-02-26 00:45 UTC, sminnee commented
Would you that be your preference?

2021-02-26 01:00 UTC, dnsl48 commented
I'd consider adding a new variable `PHPSTAN_TEST` to the default jobs (just after PHPCS_TEST) - https://github.com/silverstripe/silverstripe-travis-shared/blob/master/config/jobs/self-fixed.yml#L8

That would let us control phpstan separately from phpcs and the modules would be able to opt-out via their own travis.yml.
Then we can rely on presence of phpstan config as an explicit opt-in from the modules (as it's already done in this PR).

2021-02-26 01:29 UTC, sminnee commented
Cool, amended and force-pushed.

2021-02-26 01:42 UTC, dnsl48 approved these changes
lgtm!

2021-02-26 01:42 UTC, merged